In [22]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt

## 01 Load data

In [23]:
raw = pd.read_excel('usedcars_noisy.xlsx')
print(raw.shape)

# --- output: 160 rows, 6 columns

(160, 6)

## 02 Display contents and find noisy rows

In [24]:
raw.head(10) # display first 10 rows of the dataset

   year model  price  mileage   color transmission
0  2011   SEL  21992     7413  Yellow         AUTO
1  2011   SEL  20995    10926    Gray         AUTO
2  2011   SEL  29995       -1    Gray         AUTO
3  2011   SEL  19995     7351  Silver         AUTO
4  2011   SEL  17809    11613    Gray         AUTO
5  2012    SE  17500     8367   White         AUTO
6  2010   SEL  17495    25125  Silver         AUTO
7  2010   SES      0       -1  Silver         AUTO
8  2011   SEL  17000    27393    Blue         AUTO
9  2010   SEL  16995    21026  Silver         AUTO

### Identifying noisy rows
Using boolean mask to identify noisy rows. Each instance will be flagged if true, and false if no noise is found

In [25]:
# identifying noisy rows in price and mileage columns
noisy = (raw["price"] == 0) | (raw["mileage"] == -1)

noisy # displaying the boolean series of noisy rows

0      False
1      False
2       True
3      False
4      False
       ...
155    False
156    False
157     True
158     True
159     True
Length: 160, dtype: bool

In [26]:
# printing the number of noisy rows in price and mileage columns, including total
print("price = 0:", (raw["price"] == 0).sum(), "rows")
print("mileage = -1:", (raw["mileage"] == -1).sum(), "rows")
print("total noisy rows:", noisy.sum(), "rows") # only sums true values

raw[noisy] # displaying all the noisy rows

# --- output: 2 rows contain noise values in both price and mileage, so there are 10 rows in total

price = 0: 5 rows
mileage = -1: 7 rows
total noisy rows: 10 rows

     year model  price  mileage   color transmission
2    2011   SEL  29995       -1    Gray         AUTO
7    2010   SES      0       -1  Silver         AUTO
11   2011   SES      0     4232    Blue         AUTO
22   2011    SE  16901       -1   White         AUTO
27   2010   SES  15228       -1  Silver       MANUAL
33   2010   SEL      0    65636   Black       MANUAL
43   2010   SEL  19906       -1   White         AUTO
157  2010   SES      0    16035     Red       MANUAL
158  2005   SES   8488       -1     Red         AUTO
159  2004    SE      0       -1  Silver         AUTO

## 03 Replacing noisy values

In [ ]:
mean_price = raw["price"].mean() # calculating the mean of price column
median_mileage = raw["mileage"].median() # calculating the median of mileage column
print("mean price:", mean_price)
print("median mileage:", median_mileage)

# replacing noisy values in price and mileage columns with mean and median respectively
raw["price"] = raw["price"].replace(0, mean_price)
raw["mileage"] = raw["mileage"].replace(-1, median_mileage) 

# printing the number of noisy rows in price and mileage columns after replacement
print("price = 0:", (raw["price"] == 0).sum(), "rows")
print("mileage = -1:", (raw["mileage"] == -1).sum(), "rows") 
raw[noisy] # displaying all the noisy rows after replacement

# --- output: all noisy rows have been replaced with mean and median values

mean price: 12717.55
median mileage: 36120.0
price = 0: 0 rows
mileage = -1: 0 rows

     year model     price  mileage   color transmission
2    2011   SEL  29995.00    36120    Gray         AUTO
7    2010   SES  12717.55    36120  Silver         AUTO
11   2011   SES  12717.55     4232    Blue         AUTO
22   2011    SE  16901.00    36120   White         AUTO
27   2010   SES  15228.00    36120  Silver       MANUAL
33   2010   SEL  12717.55    65636   Black       MANUAL
43   2010   SEL  19906.00    36120   White         AUTO
157  2010   SES  12717.55    16035     Red       MANUAL
158  2005   SES   8488.00    36120     Red         AUTO
159  2004    SE  12717.55    36120  Silver         AUTO

## 04 Save cleaned data

In [32]:
raw.to_csv("usedcars_cleaned.csv", index=False) # saving the cleaned dataset to a new CSV file
print("saved", len(raw), "rows to usedcars_cleaned.csv")

cleaned_data = raw.copy() # creating a copy of the cleaned dataset

saved 160 rows to usedcars_cleaned.csv

## 06 Histograms